export const CLOUD_SOURCE = "http://8.141.164.231/qingcheng_latest";  //lixian 2022.10.11
export const BASE_ADDRESS = "http://8.141.164.231";
// export const CLOUD_SOURCE = "http://www.qingcheng.net.cn/qingcheng_latest";
// export const BASE_ADDRESS = "http://www.qingcheng.net.cn";
// export const CLOUD_SOURCE = "http://www.qingcheng.net.cn:11000/qingcheng_latest/";
// export const CLOUD_SOURCE = "http://8.141.164.231:11000/qingcheng_latest";
// export const BASE_ADDRESS = "http://8.141.164.231:11000/#";
// export const BASE_ADDRESS = "https://www.zhongkeruitong.top/qingcheng";
// export const CLOUD_SOURCE = "https://www.zhongkeruitong.top/qingcheng_latest";
